name: Build APK

on:
  push:
    branches:
      - master

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: bash ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: android/build/outputs/apk/release/*.apk
